In [1]:
#import twisted.internet.asyncioreactor
#twisted.internet.asyncioreactor.install()


import pandas as pd
import requests

import os
from pathlib import Path
import sys

import asyncio

from datetime import date, datetime, timedelta
from typing import TypedDict, List

import boto3
import json

from kayak.utils import setup_logger

In [2]:
import sys
print(sys.executable)

c:\Users\pfelz\anaconda3\envs\jedha_dts_lead\python.exe

In [3]:
import kayak
print(kayak.__file__)

C:\Pieric\datascience\JEDHA\Data Science Fundamentals\PYTHON\workspace\projects\jedha-dts-data-collect-mgmt-kayak\src\kayak\__init__.py

### Setting secrets ###

In [ ]:
import os
import ipywidgets as widgets
from IPython.display import display

style = {'description_width': 'initial'}
input_layout = widgets.Layout(width='400px')
box_layout = widgets.Layout(width='420px', margin='0 auto')

access_key = widgets.Password(description="AWS Key:")
secret_key = widgets.Password(description="AWS Secret:")
weatherforecats_api_key = widgets.Password(description="OpenWeather map api key:")
rds_postgresql_kayak_uri = widgets.Password(description="Rds postgresql kayak db URI:")

button = widgets.Button(description="Set secrets")
output = widgets.Output()

def set_env(_):
    os.environ["AWS_ACCESS_KEY_ID"] = access_key.value
    os.environ["AWS_SECRET_ACCESS_KEY"] = secret_key.value
    os.environ["OPENWEATHER_API_KEY"] = weatherforecats_api_key.value
    os.environ["RDS_KAYAK_POSTGRESQL_URI"] = rds_postgresql_kayak_uri.value
    os.environ["AWS_DEFAULT_REGION"] = "eu-west-3"

    with output:
        output.clear_output()
        print("Env variables set")

button.on_click(set_env)

form = widgets.VBox(
    [
        access_key,
        secret_key,
        weatherforecats_api_key,
        rds_postgresql_kayak_uri,
        button,
        output
    ],
    layout=box_layout
)

display(form)

VBox(children=(Password(description='AWS Key:'), Password(description='AWS Secret:'), Password(description='Op…

### Define Directories ###

In [4]:
from kayak.config.paths import DATA_DIR

#DATA_DIR = BASE_DIR / "data"
BACKUP_DIR = DATA_DIR / "backup"
INPUT_DIR = DATA_DIR / "input"
OUTPUT_DIR = DATA_DIR / "output"

def remove_file_if_exists(relative_path:str):
    if os.path.exists(relative_path):
          os.remove(relative_path)

def get_destinations_file_name() -> str:
     return "destinations.json"

### Lookup target destinations ###

In [5]:

DESTINATIONS_INPUT_FILE_PATH = INPUT_DIR / get_destinations_file_name()

with open(DESTINATIONS_INPUT_FILE_PATH, "r", encoding="utf-8") as f:
    destinations_input_info_list = json.load(f)
print('ok')

ok

In [ ]:
from kayak.config.paths import LOG_DIR
from kayak.utils import setup_logger

log_file = LOG_DIR / "kayak.log"

root_logger = setup_logger("app", log_file=str(log_file), console=False)

### Run Data ingestion Pipeline ###
##### (Collect Destination gps coordinates, collect weather forecast, calculate destination weather scores over the period and finally scarp hotels) #####

In [13]:
from kayak.pipelines import IngestionPipeline

ingestion_pipeline_logger = root_logger.getChild("ingestion-pipeline")

ingestion_pipeline = IngestionPipeline(destinations_input_info_list=destinations_input_info_list,output_dir=OUTPUT_DIR,logger=ingestion_pipeline_logger)
ingestion_outputs = ingestion_pipeline.run()
assert ingestion_outputs.destination_coordinates_output_filepath.exists()
assert ingestion_outputs.weather_forecast_output_filepath.exists()
assert ingestion_outputs.destination_weather_score_period_file_path.exists()
assert ingestion_outputs.hotel_search_param_file_name.exists()
assert ingestion_outputs.hotel_search_result_file_path.exists()

### Check data ###

##### Destination gps coordinates #####

In [14]:
dest_coordinates_dtf = pd.read_csv(str(ingestion_outputs.destination_coordinates_output_filepath), encoding='utf-8',sep=',')
dest_coordinates_dtf.head(2)

   destination_id    destination_key        destination  gps_long    gps_lat
0               1  Mont Saint Michel  Mont Saint-Michel -1.507013  48.609526
1               2         Saint-Malo         Saint-Malo -2.026041  48.649518

##### Weather forecasts #####

In [15]:
weather_forecast_dtf = pd.read_csv(str(ingestion_outputs.weather_forecast_output_filepath), encoding='utf-8',sep=',')
weather_forecast_dtf.head(2)

,destination_id,destination,dt,temp,temp_min,temp_max,pressure,humidity,weather_main,weather_descr,clouds_info_dict,pop
0,1,Mont Saint-Michel,2026-04-21 12:00:00+00:00,13.98,13.98,15.81,1019,54,Clouds,few clouds,{'all': 22},0.0
1,1,Mont Saint-Michel,2026-04-21 15:00:00+00:00,15.15,15.15,16.20,1018,56,Clouds,scattered clouds,{'all': 42},0.0

##### Destination weather scores over forecast period #####

In [16]:
destination_weather_scores_dtf = pd.read_csv(str(ingestion_outputs.destination_weather_score_period_file_path), encoding='utf-8',sep=',')
destination_weather_scores_dtf.sort_values(['weather_rank'], ascending=[True]).head(2)

,destination_id,destination,weather_median_score,avg_temp,weather_rank,start_date,end_date
21,22,Aix-en-Provence,10.0,17.71950,1,2026-04-21 12:00:00+00:00,2026-04-26 09:00:00+00:00
20,21,Marseille,10.0,17.68425,2,2026-04-21 12:00:00+00:00,2026-04-26 09:00:00+00:00

##### Hotel search common params #####

In [17]:
dtf = pd.read_csv(str(ingestion_outputs.hotel_search_param_file_name), encoding='utf-8',sep=',')
dtf.head(2)

,search_id,checkin_date,checkout_date,destination_country,destination_type,group_adults,group_children
0,1280a9ab-ebe0-4cdf-a340-74af2b3a02a2,2026-04-21,2026-04-25,France,city,2,0

##### Hotel sraping result #####

In [18]:
dtf = pd.read_csv(str(ingestion_outputs.hotel_search_result_file_path), encoding='utf-8',sep=',')
dtf.sort_values(['destination_id', 'score'], ascending = [True, False], inplace=True)
dtf.head(2)

,destination_id,hotel_name,url,gps_lat,gps_long,score,description,address,search_id
283,1,Chez Stéphanie et Matthias !,https://www.booking.com/hotel/fr/chez-stephani...,48.599615,-1.421002,10.0,"Situé à Servon, l’hébergement Chez Stéphanie e...","18 Rue du Pont Morin, 50170 Servon, France",1280a9ab-ebe0-4cdf-a340-74af2b3a02a2
291,1,Au Mont Chez Nous Jaccuzi et Sauna,https://www.booking.com/hotel/fr/26-route-de-l...,48.613455,-1.485872,9.5,"Proposant un salon commun, l’hébergement Au Mo...","26 Route de la Rive Ardevon, 50170 Pontorson, ...",1280a9ab-ebe0-4cdf-a340-74af2b3a02a2

#### Plot top destinations in a map ####

In [16]:
destination_weather_scores_dtf.dtypes

destination_id            int64
destination              object
weather_median_score    float64
avg_temp                float64
weather_rank              int64
start_date               object
end_date                 object
dtype: object

##### Preprocessing to display top destinations on a map  (join gps coordinates, typing...) #####

In [19]:
TOP_N_DESTINATION = 5

top_destination_dtf = destination_weather_scores_dtf.sort_values(['weather_rank'], ascending=[True]).head(TOP_N_DESTINATION)
top_destination_dtf = pd.merge(left=top_destination_dtf, right=dest_coordinates_dtf, on='destination_id', how='left')
top_destination_dtf.drop(['destination_y'], axis=1, inplace=True)
top_destination_dtf.rename(columns={'destination_x':'destination'}, inplace=True)
top_destination_dtf['gps_long']= top_destination_dtf['gps_long'].astype(float)
top_destination_dtf['gps_lat'] = top_destination_dtf['gps_lat'].astype(float)
top_destination_dtf['start_date'] = pd.to_datetime(top_destination_dtf['start_date'], utc=True)
top_destination_dtf['end_date'] = pd.to_datetime(top_destination_dtf['end_date'], utc=True)
top_destination_dtf.head(2)

,destination_id,destination,weather_median_score,avg_temp,weather_rank,start_date,end_date,destination_key,gps_long,gps_lat
0,22,Aix-en-Provence,10.0,17.71950,1,2026-04-21 12:00:00+00:00,2026-04-26 09:00:00+00:00,Aix en Provence,5.447474,43.529842
1,21,Marseille,10.0,17.68425,2,2026-04-21 12:00:00+00:00,2026-04-26 09:00:00+00:00,Marseille,5.369953,43.296174

In [13]:
import plotly.express as px
# play with the color: continous/numerical
#px.set_mapbox_access_token(open(".mapbox_token").read())
weather_forecast_start_date = top_destination_dtf.iloc[0]['start_date']
weather_forecast_end_date = top_destination_dtf.iloc[0]['end_date']
fig = px.scatter_mapbox(top_destination_dtf, lat="gps_lat", lon="gps_long", color="weather_rank", text='destination', 
#                         size="hour",
                        #color_continuous_scale=px.colors.cyclical.IceFire,   
                        color_continuous_scale="RdYlGn_r",                     
                        zoom=4.5,
                       width=900,
                        height=600,
                        labels={'median_temp' : 'median temperature'},
                        title='Top 5 destinations ' + weather_forecast_start_date.strftime("%d-%m-%Y") + ' to ' + weather_forecast_end_date.strftime("%d-%m-%Y"))
fig.update_traces(marker=dict(size=20))
fig.update_layout(mapbox_style="open-street-map")
fig.show()

In [14]:
#!pip show kaleido
import importlib

print(importlib.util.find_spec("kaleido") is not None)

True

In [15]:
#fig.write_image("kayak_top5destinations.png")
fig.write_html("kayak_top5destinations.html")

#### Display Top-20 hotels for each of top-5 destinations in a map ####

##### Select Top-20 hotels for each of top-5 destinations #####

In [20]:
destination_hotels_dtf = pd.read_csv(str(ingestion_outputs.hotel_search_result_file_path), encoding='utf-8',sep=',')

top_hotels_dtf  = destination_hotels_dtf[destination_hotels_dtf['destination_id'].isin(top_destination_dtf['destination_id'].unique())].copy()
top_hotels_dtf.fillna({'score':0}, inplace=True)
top_hotels_dtf['hotel_rank'] = top_hotels_dtf.groupby('destination_id')['score'].rank(method='first',ascending=False).astype(int)
top_hotels_dtf  = top_hotels_dtf[(top_hotels_dtf['hotel_rank'] <= 20 )]

# result just to display the two best rated hotels of the two top destinations in term of weather rank
result = top_hotels_dtf[
    (top_hotels_dtf['destination_id'].isin(top_destination_dtf.loc[top_destination_dtf['weather_rank']<=2, 'destination_id'])) &
    (top_hotels_dtf['hotel_rank'] <= 2)
].sort_values(['destination_id', 'hotel_rank'])

#top_hotels_dtf.dtypes
result

,destination_id,hotel_name,url,gps_lat,gps_long,score,description,address,search_id,hotel_rank
831,21,Entre Plages et Jardins,https://www.booking.com/hotel/fr/entre-mer-et-...,43.250530,5.381482,9.5,"Offrant une vue sur le jardin, l’hébergement E...","72 Boulevard du Sablier, 13008 Marseille, France",1280a9ab-ebe0-4cdf-a340-74af2b3a02a2,1
477,21,Le Central Parc - T2-Spacieux-Clim-Wifi,https://www.booking.com/hotel/fr/le-central-pa...,43.281857,5.396548,9.4,L’hébergement 5 étoiles Le Central Parc - T2-S...,"27 Rue Paul Casimir, 13010 Marseille, France",1280a9ab-ebe0-4cdf-a340-74af2b3a02a2,2
821,22,T3 Centre ville Aix-en-Provence,https://www.booking.com/hotel/fr/t3-centre-vil...,43.521985,5.453696,9.8,L’hébergement T3 Centre ville Aix-en-Provence ...,"Bat D 1er etage 29 Avenue Saint-Jérôme, 13100 ...",1280a9ab-ebe0-4cdf-a340-74af2b3a02a2,1
807,22,Bed and Breakfast Jardin de Marie,https://www.booking.com/hotel/fr/le-jardin-de-...,43.524902,5.450541,9.1,"Situé à Aix-en-Provence, le Bed and Breakfast ...","47, rue Roux Alphéran, 13100 Aix-en-Provence, ...",1280a9ab-ebe0-4cdf-a340-74af2b3a02a2,2

In [15]:
# play with the color: continous/numerical
#px.set_mapbox_access_token(open(".mapbox_token").read())
import plotly.express as px
fig = px.scatter_mapbox(top_hotels_dtf, lat="gps_lat", lon="gps_long", color="score", text='hotel_name',
#                         size="hour",
                        color_continuous_scale=px.colors.cyclical.IceFire,                        
                        zoom=4.5,
                       width=900,
                        height=600,
                        labels={'score' : 'hotel score'},
                        title='Top hotels ' + weather_forecast_start_date.strftime("%d-%m-%Y") + ' to ' + weather_forecast_end_date.strftime("%d-%m-%Y"))
fig.update_traces(marker=dict(size=20))
fig.update_layout(mapbox_style="open-street-map")
fig.show()

In [14]:
fig.write_html("kayak_top20hotels_top5destinations.html")

### Export csvs to S3 (Storage pipeline) ###

In [22]:
from kayak.services import S3Service
import importlib

from kayak.pipelines import StoragePipeline,StoragePipelineOutput

In [23]:
session = boto3.Session()
S3_BUCKET_NAME = "pfe-kayak-bucket"
storage_pipeline_logger = root_logger.getChild("storage-pipeline")
s3_service = S3Service(S3_BUCKET_NAME,session,storage_pipeline_logger)
storage_pipeline = StoragePipeline(s3_service)

In [24]:
storage_output = storage_pipeline.upload_files(ingestion_outputs.to_file_list())

In [25]:
for s3_key in storage_output.uploaded_keys:
    print(s3_key)

csv/destination_gps_coordinates.csv
csv/weather/destination_weather_forecast_20260421T1200_20260426T0900.csv
csv/weather/destination_weather_scores_20260421T1200_20260426T0900.csv
csv/hotels/hotel_search_param_20260421T1200_20260426T0900.csv
csv/hotels/hotel_search_results_20260421T1200_20260426T0900.csv

### Load files stored on S3 with storage pipeline (LoadPipeline) ###

In [8]:
from kayak.pipelines import LoadPipeline
from kayak.services import S3Service

TEMP_DIR =  DATA_DIR / "temp"
TEMP_DIR.mkdir(parents=True, exist_ok=True)

In [29]:
load_pipeline_logger = root_logger.getChild("load-pipeline")
load_pipeline = LoadPipeline(s3_service, TEMP_DIR,load_pipeline_logger)
file_path_list = load_pipeline.run(s3_keys=storage_output.uploaded_keys)

In [15]:

TEMP_DIR =  DATA_DIR / "temp"
TEMP_CSV_DIR = TEMP_DIR / "csv"
file_path_list = [
    TEMP_CSV_DIR / "destination_gps_coordinates.csv",
    TEMP_CSV_DIR / "weather" / "destination_weather_forecast_20260421T1200_20260426T0900.csv",
    TEMP_CSV_DIR / "weather" / "destination_weather_scores_20260421T1200_20260426T0900.csv",
    TEMP_CSV_DIR / "hotels" / "hotel_search_param_20260421T1200_20260426T0900.csv",
    TEMP_CSV_DIR / "hotels" / "hotel_search_results_20260421T1200_20260426T0900.csv",
]

for path in file_path_list:
    print(path, "->", path.exists())

C:\Pieric\datascience\JEDHA\Data Science Fundamentals\PYTHON\workspace\projects\jedha-dts-data-collect-mgmt-kayak\data\temp\csv\destination_gps_coordinates.csv -> True
C:\Pieric\datascience\JEDHA\Data Science Fundamentals\PYTHON\workspace\projects\jedha-dts-data-collect-mgmt-kayak\data\temp\csv\weather\destination_weather_forecast_20260421T1200_20260426T0900.csv -> True
C:\Pieric\datascience\JEDHA\Data Science Fundamentals\PYTHON\workspace\projects\jedha-dts-data-collect-mgmt-kayak\data\temp\csv\weather\destination_weather_scores_20260421T1200_20260426T0900.csv -> True
C:\Pieric\datascience\JEDHA\Data Science Fundamentals\PYTHON\workspace\projects\jedha-dts-data-collect-mgmt-kayak\data\temp\csv\hotels\hotel_search_param_20260421T1200_20260426T0900.csv -> True
C:\Pieric\datascience\JEDHA\Data Science Fundamentals\PYTHON\workspace\projects\jedha-dts-data-collect-mgmt-kayak\data\temp\csv\hotels\hotel_search_results_20260421T1200_20260426T0900.csv -> True

### Transform and load models to RDS Postgresql DB (DWH Pipeline) ###

In [16]:
import importlib
import kayak.pipelines

importlib.reload(kayak.pipelines)

In [17]:
from sqlalchemy import create_engine
from kayak.pipelines import DWHPipeline

# Make sure psycopg2-binary is installed on the kernel / anaconda environment pip install psycopg2-binary
rds_postgres_engine = create_engine(os.getenv("RDS_KAYAK_POSTGRESQL_URI"), echo=True)
dwh_pipeline_logger = root_logger.getChild("dwh-pipeline")

from kayak.models import Base

Base.metadata.create_all(rds_postgres_engine)

dwh_pipeline = DWHPipeline(rds_postgres_engine, dwh_pipeline_logger)
dwh_pipeline.run(file_path_list)

2026-04-21 12:54:19,518 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2026-04-21 12:54:19,518 INFO sqlalchemy.engine.Engine [raw sql] {}
2026-04-21 12:54:19,618 INFO sqlalchemy.engine.Engine select current_schema()
2026-04-21 12:54:19,619 INFO sqlalchemy.engine.Engine [raw sql] {}
2026-04-21 12:54:19,717 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2026-04-21 12:54:19,718 INFO sqlalchemy.engine.Engine [raw sql] {}
2026-04-21 12:54:19,818 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2026-04-21 12:54:19,823 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2026-04-21 12:54:19,825 INFO sqlalchemy.engine.Engine [generated in 0.00162s] {'table_name': 'destination', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2026-04-21 12:54:19,927 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2026-04-21 12:54:19,928 INFO sqlalchemy.engine.Engine [cached since 0.1058s ago] {'table_name': 'destination_weather_forecast', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2026-04-21 12:54:19,978 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2026-04-21 12:54:19,979 INFO sqlalchemy.engine.Engine [cached since 0.1562s ago] {'table_name': 'destination_weather_score_period', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2026-04-21 12:54:20,027 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2026-04-21 12:54:20,030 INFO sqlalchemy.engine.Engine [cached since 0.2068s ago] {'table_name': 'hotel_search_param', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2026-04-21 12:54:20,077 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2026-04-21 12:54:20,078 INFO sqlalchemy.engine.Engine [cached since 0.2555s ago] {'table_name': 'hotel_search_result', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2026-04-21 12:54:20,117 INFO sqlalchemy.engine.Engine COMMIT
2026-04-21 12:54:20,189 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2026-04-21 12:54:20,194 INFO sqlalchemy.engine.Engine INSERT INTO destination (destination_id, destination_key, destination, gps_long, gps_lat) VALUES (%(destination_id_m0)s, %(destination_key_m0)s, %(destination_m0)s, %(gps_long_m0)s, %(gps_lat_m0)s), (%(destination_id_m1)s, %(destination_key_m1)s, %(destination_m1)s, %(gps_long_m1)s, %(gps_lat_m1)s), (%(destination_id_m2)s, %(destination_key_m2)s, %(destination_m2)s, %(gps_long_m2)s, %(gps_lat_m2)s), (%(destination_id_m3)s, %(destination_key_m3)s, %(destination_m3)s, %(gps_long_m3)s, %(gps_lat_m3)s), (%(destination_id_m4)s, %(destination_key_m4)s, %(destination_m4)s, %(gps_long_m4)s, %(gps_lat_m4)s), (%(destination_id_m5)s, %(destination_key_m5)s, %(destination_m5)s, %(gps_long_m5)s, %(gps_lat_m5)s), (%(destination_id_m6)s, %(destination_key_m6)s, %(destination_m6)s, %(gps_long_m6)s, %(gps_lat_m6)s), (%(destination_id_m7)s, %(destination_key_m7)s, %(destination_m7)s, %(gps_long_m7)s, %(gps_lat_m7)s), (%(destination_id_m8)s, %(destination_key_m8)s, %(destination_m8)s, %(gps_long_m8)s, %(gps_lat_m8)s), (%(destination_id_m9)s, %(destination_key_m9)s, %(destination_m9)s, %(gps_long_m9)s, %(gps_lat_m9)s), (%(destination_id_m10)s, %(destination_key_m10)s, %(destination_m10)s, %(gps_long_m10)s, %(gps_lat_m10)s), (%(destination_id_m11)s, %(destination_key_m11)s, %(destination_m11)s, %(gps_long_m11)s, %(gps_lat_m11)s), (%(destination_id_m12)s, %(destination_key_m12)s, %(destination_m12)s, %(gps_long_m12)s, %(gps_lat_m12)s), (%(destination_id_m13)s, %(destination_key_m13)s, %(destination_m13)s, %(gps_long_m13)s, %(gps_lat_m13)s), (%(destination_id_m14)s, %(destination_key_m14)s, %(destination_m14)s, %(gps_long_m14)s, %(gps_lat_m14)s), (%(destination_id_m15)s, %(destination_key_m15)s, %(destination_m15)s, %(gps_long_m15)s, %(gps_lat_m15)s), (%(destination_id_m16)s, %(destination_key_m16)s, %(destination_m16)s, %(gps_long_m16)s, %(gps_lat_m16)s), (%(destination_id_m17)s, %(destination_key_m17)s, %(destination_m17)s, %(gps_long_m17)s, %(gps_lat_m17)s), (%(destination_id_m18)s, %(destination_key_m18)s, %(destination_m18)s, %(gps_long_m18)s, %(gps_lat_m18)s), (%(destination_id_m19)s, %(destination_key_m19)s, %(destination_m19)s, %(gps_long_m19)s, %(gps_lat_m19)s), (%(destination_id_m20)s, %(destination_key_m20)s, %(destination_m20)s, %(gps_long_m20)s, %(gps_lat_m20)s), (%(destination_id_m21)s, %(destination_key_m21)s, %(destination_m21)s, %(gps_long_m21)s, %(gps_lat_m21)s), (%(destination_id_m22)s, %(destination_key_m22)s, %(destination_m22)s, %(gps_long_m22)s, %(gps_lat_m22)s), (%(destination_id_m23)s, %(destination_key_m23)s, %(destination_m23)s, %(gps_long_m23)s, %(gps_lat_m23)s), (%(destination_id_m24)s, %(destination_key_m24)s, %(destination_m24)s, %(gps_long_m24)s, %(gps_lat_m24)s), (%(destination_id_m25)s, %(destination_key_m25)s, %(destination_m25)s, %(gps_long_m25)s, %(gps_lat_m25)s), (%(destination_id_m26)s, %(destination_key_m26)s, %(destination_m26)s, %(gps_long_m26)s, %(gps_lat_m26)s), (%(destination_id_m27)s, %(destination_key_m27)s, %(destination_m27)s, %(gps_long_m27)s, %(gps_lat_m27)s), (%(destination_id_m28)s, %(destination_key_m28)s, %(destination_m28)s, %(gps_long_m28)s, %(gps_lat_m28)s), (%(destination_id_m29)s, %(destination_key_m29)s, %(destination_m29)s, %(gps_long_m29)s, %(gps_lat_m29)s), (%(destination_id_m30)s, %(destination_key_m30)s, %(destination_m30)s, %(gps_long_m30)s, %(gps_lat_m30)s), (%(destination_id_m31)s, %(destination_key_m31)s, %(destination_m31)s, %(gps_long_m31)s, %(gps_lat_m31)s), (%(destination_id_m32)s, %(destination_key_m32)s, %(destination_m32)s, %(gps_long_m32)s, %(gps_lat_m32)s), (%(destination_id_m33)s, %(destination_key_m33)s, %(destination_m33)s, %(gps_long_m33)s, %(gps_lat_m33)s), (%(destination_id_m34)s, %(destination_key_m34)s, %(destination_m34)s, %(gps_long_m34)s, %(gps_lat_m34)s) ON CONFLICT (destination_id) DO NOTHING
2026-04-21 12:54:20,195 INFO sqlalchemy.engine.Engine [no key 0.00124s] {'destination_id_m0': 1, 'destination_key_m0': 'Mont Saint Michel', 'destination_m0': 'Mont Saint-Michel', 'gps_long_m0': -1.5070125, 'gps_lat_m0': 48.6095263, 'destination_id_m1': 2, 'destination_key_m1': 'Saint-Malo', 'destination_m1': 'Saint-Malo', 'gps_long_m1': -2.0260409, 'gps_lat_m1': 48.649518, 'destination_id_m2': 3, 'destination_key_m2': 'Bayeux', 'destination_m2': 'Bayeux', 'gps_long_m2': -0.7024738, 'gps_lat_m2': 49.2764624, 'destination_id_m3': 4, 'destination_key_m3': 'Le Havre', 'destination_m3': 'Le Havre', 'gps_long_m3': 0.1079732, 'gps_lat_m3': 49.4938975, 'destination_id_m4': 5, 'destination_key_m4': 'Rouen', 'destination_m4': 'Rouen', 'gps_long_m4': 1.0939658, 'gps_lat_m4': 49.4404591, 'destination_id_m5': 6, 'destination_key_m5': 'Paris', 'destination_m5': 'Paris', 'gps_long_m5': 2.3483915, 'gps_lat_m5': 48.8534951, 'destination_id_m6': 7, 'destination_key_m6': 'Amiens', 'destination_m6': 'Amiens', 'gps_long_m6': 2.2956951, 'gps_lat_m6': 49.8941708, 'destination_id_m7': 8, 'destination_key_m7': 'Lille', 'destination_m7': 'Lille', 'gps_long_m7': 3.0635282, 'gps_lat_m7': 50.6365654, 'destination_id_m8': 9, 'destination_key_m8': 'Strasbourg', 'destination_m8': 'Strasbourg', 'gps_long_m8': 7.7507127, 'gps_lat_m8': 48.584614, 'destination_id_m9': 10, 'destination_key_m9': 'Château du Haut Koenigsbourg', 'destination_m9': 'Château du Haut-Kœnigsbourg', 'gps_long_m9': 7.3443202, 'gps_lat_m9': 48.2494107 ... 75 parameters truncated ... 'destination_id_m25': 26, 'destination_key_m25': 'Aigues Mortes', 'destination_m25': 'Aigues-Mortes', 'gps_long_m25': 4.19154, 'gps_lat_m25': 43.5661521, 'destination_id_m26': 27, 'destination_key_m26': 'Saintes Maries de la mer', 'destination_m26': 'Saintes-Maries-de-la-Mer', 'gps_long_m26': 4.4277202, 'gps_lat_m26': 43.4515922, 'destination_id_m27': 28, 'destination_key_m27': 'Collioure', 'destination_m27': 'Collioure', 'gps_long_m27': 3.0831554, 'gps_lat_m27': 42.52505, 'destination_id_m28': 29, 'destination_key_m28': 'Carcassonne', 'destination_m28': 'Carcassonne', 'gps_long_m28': 2.3491069, 'gps_lat_m28': 43.2130358, 'destination_id_m29': 30, 'destination_key_m29': 'Ariege', 'destination_m29': 'Ariège', 'gps_long_m29': 1.4065544, 'gps_lat_m29': 42.9455368, 'destination_id_m30': 31, 'destination_key_m30': 'Toulouse', 'destination_m30': 'Toulouse', 'gps_long_m30': 1.4442469, 'gps_lat_m30': 43.6044622, 'destination_id_m31': 32, 'destination_key_m31': 'Montauban', 'destination_m31': 'Montauban', 'gps_long_m31': 1.3549991, 'gps_lat_m31': 44.0175835, 'destination_id_m32': 33, 'destination_key_m32': 'Biarritz', 'destination_m32': 'Biarritz', 'gps_long_m32': -1.5592776, 'gps_lat_m32': 43.4832523, 'destination_id_m33': 34, 'destination_key_m33': 'Bayonne', 'destination_m33': 'Bayonne', 'gps_long_m33': -1.4736657, 'gps_lat_m33': 43.4945144, 'destination_id_m34': 35, 'destination_key_m34': 'La Rochelle', 'destination_m34': 'La Rochelle', 'gps_long_m34': -1.1515951, 'gps_lat_m34': 46.159732}
2026-04-21 12:54:20,338 INFO sqlalchemy.engine.Engine DELETE FROM destination_weather_forecast WHERE destination_weather_forecast.dt >= %(dt_1)s AND destination_weather_forecast.dt <= %(dt_2)s
2026-04-21 12:54:20,339 INFO sqlalchemy.engine.Engine [generated in 0.00108s] {'dt_1': Timestamp('2026-04-21 12:00:00+0000', tz='UTC'), 'dt_2': Timestamp('2026-04-26 09:00:00+0000', tz='UTC')}
2026-04-21 12:54:20,429 INFO sqlalchemy.engine.Engine INSERT INTO destination_weather_forecast (destination_id, dt, temp, temp_min, temp_max, pressure, humidity, weather_main, weather_descr, clouds_info_dict, pop) VALUES (%(destination_id__0)s, %(dt__0)s, %(temp__0)s, %(temp_min__0)s, %(temp_max__0)s, % ... 224605 characters truncated ... 99)s, %(weather_main__999)s, %(weather_descr__999)s, %(clouds_info_dict__999)s::JSONB, %(pop__999)s)
2026-04-21 12:54:20,430 INFO sqlalchemy.engine.Engine [generated in 0.01011s (insertmanyvalues) 1/2 (unordered)] {'temp_max__0': 15.81, 'clouds_info_dict__0': '{"all": 22}', 'pressure__0': 1019, 'pop__0': 0.0, 'temp__0': 13.98, 'weather_main__0': 'Clouds', 'dt__0': Timestamp('2026-04-21 12:00:00+0000', tz='UTC'), 'destination_id__0': 1, 'temp_min__0': 13.98, 'humidity__0': 54, 'weather_descr__0': 'few clouds', 'temp_max__1': 16.2, 'clouds_info_dict__1': '{"all": 42}', 'pressure__1': 1018, 'pop__1': 0.0, 'temp__1': 15.15, 'weather_main__1': 'Clouds', 'dt__1': Timestamp('2026-04-21 15:00:00+0000', tz='UTC'), 'destination_id__1': 1, 'temp_min__1': 15.15, 'humidity__1': 56, 'weather_descr__1': 'scattered clouds', 'temp_max__2': 14.28, 'clouds_info_dict__2': '{"all": 49}', 'pressure__2': 1017, 'pop__2': 0.0, 'temp__2': 14.28, 'weather_main__2': 'Clouds', 'dt__2': Timestamp('2026-04-21 18:00:00+0000', tz='UTC'), 'destination_id__2': 1, 'temp_min__2': 14.28, 'humidity__2': 65, 'weather_descr__2': 'scattered clouds', 'temp_max__3': 11.74, 'clouds_info_dict__3': '{"all": 67}', 'pressure__3': 1018, 'pop__3': 0.0, 'temp__3': 11.74, 'weather_main__3': 'Clouds', 'dt__3': Timestamp('2026-04-21 21:00:00+0000', tz='UTC'), 'destination_id__3': 1, 'temp_min__3': 11.74, 'humidity__3': 68, 'weather_descr__3': 'broken clouds', 'temp_max__4': 11.69, 'clouds_info_dict__4': '{"all": 71}', 'pressure__4': 1017, 'pop__4': 0.0, 'temp__4': 11.69, 'weather_main__4': 'Clouds' ... 10900 parameters truncated ... 'weather_main__995': 'Clouds', 'dt__995': Timestamp('2026-04-25 21:00:00+0000', tz='UTC'), 'destination_id__995': 25, 'temp_min__995': 16.73, 'humidity__995': 68, 'weather_descr__995': 'broken clouds', 'temp_max__996': 15.35, 'clouds_info_dict__996': '{"all": 29}', 'pressure__996': 1015, 'pop__996': 0.0, 'temp__996': 15.35, 'weather_main__996': 'Clouds', 'dt__996': Timestamp('2026-04-26 00:00:00+0000', tz='UTC'), 'destination_id__996': 25, 'temp_min__996': 15.35, 'humidity__996': 66, 'weather_descr__996': 'scattered clouds', 'temp_max__997': 13.71, 'clouds_info_dict__997': '{"all": 7}', 'pressure__997': 1015, 'pop__997': 0.0, 'temp__997': 13.71, 'weather_main__997': 'Clear', 'dt__997': Timestamp('2026-04-26 03:00:00+0000', tz='UTC'), 'destination_id__997': 25, 'temp_min__997': 13.71, 'humidity__997': 72, 'weather_descr__997': 'clear sky', 'temp_max__998': 13.81, 'clouds_info_dict__998': '{"all": 16}', 'pressure__998': 1016, 'pop__998': 0.0, 'temp__998': 13.81, 'weather_main__998': 'Clouds', 'dt__998': Timestamp('2026-04-26 06:00:00+0000', tz='UTC'), 'destination_id__998': 25, 'temp_min__998': 13.81, 'humidity__998': 67, 'weather_descr__998': 'few clouds', 'temp_max__999': 20.66, 'clouds_info_dict__999': '{"all": 35}', 'pressure__999': 1016, 'pop__999': 0.0, 'temp__999': 20.66, 'weather_main__999': 'Clouds', 'dt__999': Timestamp('2026-04-26 09:00:00+0000', tz='UTC'), 'destination_id__999': 25, 'temp_min__999': 20.66, 'humidity__999': 42, 'weather_descr__999': 'scattered clouds'}
2026-04-21 12:54:20,786 INFO sqlalchemy.engine.Engine INSERT INTO destination_weather_forecast (destination_id, dt, temp, temp_min, temp_max, pressure, humidity, weather_main, weather_descr, clouds_info_dict, pop) VALUES (%(destination_id__0)s, %(dt__0)s, %(temp__0)s, %(temp_min__0)s, %(temp_max__0)s, % ... 89005 characters truncated ... 99)s, %(weather_main__399)s, %(weather_descr__399)s, %(clouds_info_dict__399)s::JSONB, %(pop__399)s)
2026-04-21 12:54:20,787 INFO sqlalchemy.engine.Engine [insertmanyvalues 2/2 (unordered)] {'temp_max__0': 21.86, 'clouds_info_dict__0': '{"all": 20}', 'pressure__0': 1011, 'pop__0': 0.0, 'temp__0': 21.86, 'weather_main__0': 'Clouds', 'dt__0': Timestamp('2026-04-21 12:00:00+0000', tz='UTC'), 'destination_id__0': 26, 'temp_min__0': 21.69, 'humidity__0': 47, 'weather_descr__0': 'few clouds', 'temp_max__1': 21.63, 'clouds_info_dict__1': '{"all": 5}', 'pressure__1': 1010, 'pop__1': 0.0, 'temp__1': 21.63, 'weather_main__1': 'Clear', 'dt__1': Timestamp('2026-04-21 15:00:00+0000', tz='UTC'), 'destination_id__1': 26, 'temp_min__1': 21.47, 'humidity__1': 50, 'weather_descr__1': 'clear sky', 'temp_max__2': 17.9, 'clouds_info_dict__2': '{"all": 12}', 'pressure__2': 1010, 'pop__2': 0.42, 'temp__2': 17.9, 'weather_main__2': 'Rain', 'dt__2': Timestamp('2026-04-21 18:00:00+0000', tz='UTC'), 'destination_id__2': 26, 'temp_min__2': 17.9, 'humidity__2': 72, 'weather_descr__2': 'light rain', 'temp_max__3': 16.14, 'clouds_info_dict__3': '{"all": 60}', 'pressure__3': 1011, 'pop__3': 0.39, 'temp__3': 16.14, 'weather_main__3': 'Rain', 'dt__3': Timestamp('2026-04-21 21:00:00+0000', tz='UTC'), 'destination_id__3': 26, 'temp_min__3': 16.14, 'humidity__3': 68, 'weather_descr__3': 'light rain', 'temp_max__4': 14.05, 'clouds_info_dict__4': '{"all": 79}', 'pressure__4': 1011, 'pop__4': 0.0, 'temp__4': 14.05, 'weather_main__4': 'Clouds' ... 4300 parameters truncated ... 'weather_main__395': 'Clouds', 'dt__395': Timestamp('2026-04-25 21:00:00+0000', tz='UTC'), 'destination_id__395': 35, 'temp_min__395': 15.06, 'humidity__395': 79, 'weather_descr__395': 'overcast clouds', 'temp_max__396': 12.95, 'clouds_info_dict__396': '{"all": 100}', 'pressure__396': 1018, 'pop__396': 0.0, 'temp__396': 12.95, 'weather_main__396': 'Clouds', 'dt__396': Timestamp('2026-04-26 00:00:00+0000', tz='UTC'), 'destination_id__396': 35, 'temp_min__396': 12.95, 'humidity__396': 75, 'weather_descr__396': 'overcast clouds', 'temp_max__397': 11.46, 'clouds_info_dict__397': '{"all": 42}', 'pressure__397': 1018, 'pop__397': 0.0, 'temp__397': 11.46, 'weather_main__397': 'Clouds', 'dt__397': Timestamp('2026-04-26 03:00:00+0000', tz='UTC'), 'destination_id__397': 35, 'temp_min__397': 11.46, 'humidity__397': 78, 'weather_descr__397': 'scattered clouds', 'temp_max__398': 10.48, 'clouds_info_dict__398': '{"all": 31}', 'pressure__398': 1019, 'pop__398': 0.0, 'temp__398': 10.48, 'weather_main__398': 'Clouds', 'dt__398': Timestamp('2026-04-26 06:00:00+0000', tz='UTC'), 'destination_id__398': 35, 'temp_min__398': 10.48, 'humidity__398': 75, 'weather_descr__398': 'scattered clouds', 'temp_max__399': 14.38, 'clouds_info_dict__399': '{"all": 76}', 'pressure__399': 1019, 'pop__399': 0.0, 'temp__399': 14.38, 'weather_main__399': 'Clouds', 'dt__399': Timestamp('2026-04-26 09:00:00+0000', tz='UTC'), 'destination_id__399': 35, 'temp_min__399': 14.38, 'humidity__399': 70, 'weather_descr__399': 'broken clouds'}
2026-04-21 12:54:20,961 INFO sqlalchemy.engine.Engine DELETE FROM destination_weather_score_period WHERE destination_weather_score_period.start_date >= %(start_date_1)s AND destination_weather_score_period.end_date <= %(end_date_1)s
2026-04-21 12:54:20,961 INFO sqlalchemy.engine.Engine [generated in 0.00076s] {'start_date_1': Timestamp('2026-04-21 12:00:00+0000', tz='UTC'), 'end_date_1': Timestamp('2026-04-26 09:00:00+0000', tz='UTC')}
2026-04-21 12:54:21,019 INFO sqlalchemy.engine.Engine INSERT INTO destination_weather_score_period (destination_id, weather_median_score, avg_temp, weather_rank, start_date, end_date) VALUES (%(destination_id__0)s, %(weather_median_score__0)s, %(avg_temp__0)s, %(weather_rank__0)s, %(start_date__0)s, %(e ... 4415 characters truncated ... er_median_score__34)s, %(avg_temp__34)s, %(weather_rank__34)s, %(start_date__34)s, %(end_date__34)s)